name: Release
on:
  push:
    branches:
      - trunk
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.0
      - name: setup node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
      - name: install dependencies
        run: |
          npm install
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
