name: release
on:
  push:
    branches:
      - trunk
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4.0.0
      - name: setup node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 'lts/*'
      - name: upgrade npm
        run: npm install -g npm
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: test
        run: pnpm run test
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec semantic-release
